### ISSUE TITLE
DB interface issue for both db/sql & db/pgx

### ISSUE THREAD

**Issue by chentihe** [iden3/go-merkletree-sql#20]
I tried to use this package to create merkle tree on backend, but when I connect with postgres by pgx, the error occurred.
Here's error message
```
cannot use pgxPool (variable of type *pgxpool.Pool) as "github.com/iden3/go-merkletree-sql/db/pgx/v2".DB value in argument to sql.NewSqlStorage: *pgxpool.Pool does not implement "github.com/iden3/go-merkletree-sql/db/pgx/v2".DB (wrong type for method Exec)
                have Exec(context.Context, string, ...any) ("github.com/jackc/pgx/v5/pgconn".CommandTag, error)
                want Exec(context.Context, string, ...interface{}) ("github.com/jackc/pgconn".CommandTag, error)
```

I found both `sql.go` on db/sql and db/pgx share the same interface of DB. Should these two interfaces change the type of args from ...interface{} to ...any?

```go
type DB interface {
	ExecContext(ctx context.Context, query string, args ...interface{}) (sql.Result, error)
	GetContext(ctx context.Context, dest interface{}, query string, args ...interface{}) error
	SelectContext(ctx context.Context, dest interface{}, query string, args ...interface{}) error
}
```

**Comment by chentihe** [comment]
I ran the `sql_test.go` script of db/pgx, test cases are all passed, but I found an issue is that the `go-test-pg` is using `pgx/v4` package to create the pgxPool instead of `pgx/v5`, you can see the type of args on `pgx/v4` is ...interface{}.
![image](https://github.com/iden3/go-merkletree-sql/assets/48288259/0f0e1bd6-1f04-4b7e-89a2-3af1c13372d4)

Based on [go-test-pg](https://github.com/olomix/go-test-pg/tree/master), to test pgx/v5 the version should swtich to v2.

**Comment by chentihe** [comment]
I found out that you have a folder `v5` under pgx folder which is for `pgx/v5`. But I cannot use this package by `github.com/iden3/go-merkletree-sql/v2/db/pgx/v5`, `github.com/iden3/go-merkletree-sql/db/pgx/v2` is the package I can use, but the pgx driver in that package is v4 not v5, please check.

**Comment by OBrezhniev** [comment]
@chentihe Try to use `github.com/iden3/go-merkletree-sql/db/pgx/v5` instead of `github.com/iden3/go-merkletree-sql/v2/db/pgx/v5`

**Comment by chentihe** [comment]
@OBrezhniev 
thanks, it works, maybe the README.md should update so that the developer is able to using correct package ~
